name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, bcmath, zip, fileinfo
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

      - name: Install NPM Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Prepare Windows Package
        shell: pwsh
        run: .\build\scripts\prepare-package.ps1

      - name: Compile Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.7
        with:
          path: build/installer.iss

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: enapel-server-windows-installer
          path: dist/enapel-server.exe
